### ISSUE TITLE
Introduce iterator/reader iteration macro

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#104]
**Reported by rich on 9 Mar 2015 06:01 UTC**
A macro should be introduced for iterating through the elements of a reader. The macro should accept a zero-argument block which specifies the body. The loop variable is declared outside of the macro, and its type is inferred to be the element type of the supplied set.

So instead of writing this:

```
For each of aReader do
[: any
|
    Print: elem ++ "\n";
](
    elem);
```

One could write:

```
For each elem of aReader do
[elem ++ "\n";
](
    Print:);
```

The macro should produce a send of "For each of_do_" [[](reader,)] with appropriate arguments.

The library should be updated to use the new macro wherever possible.

**Comment by leslieATavail** [comment]
This seems to have already been implemented.
