### ISSUE TITLE
Building and Installing on Windows 7

### ISSUE THREAD

**Issue by rupipal** [AvailLang/Avail#120]
Hi, 
The user mailing list here isn't available here
http://www.availlang.org/about-avail/download/get-source.html

So I am raising my question here.

I built and installed Avail on windows 7. However, in the install directory bin, I'm getting bash scripts avail-dev and avail-server. Obviously, I can't launch them. Could somebody help?

regards
Rupinder

**Comment by ulidtko** [comment]
> Obviously, I can't launch them.

Obviously?.. You actually can run bash on windows. http://www.msys2.org/

**Comment by markATavail** [comment]
First, apologies for the Windows instructions being out of date.  We're working on significant changes to the website, and really should have updated that page specifically some time ago.

I can't verify if a bash shell is sufficient to get Avail to launch on Windows, but I recently have had to step back into the Windows world and built a workaround for launching Avail.  Have a look at distro/bin/Windows/AvailWorkbench.bat.  I've successfully used this batch file to launch Avail on Windows 7.  You'll need to change line 3 for your specific configuration.

**Comment by markATavail** [comment]
Closing, even though the web site needs an update.
