### ISSUE TITLE
Argument reordering cannot be used with argument group modifiers

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#128]
A shortcoming in `MessageSplitter` currently forbids modified argument groups (e.g., `«something_»?`) from being reordered (e.g., `«something_»?②`).

**Comment by markATavail** [comment]
In development branch, Decompiler Tests.avail now correctly tests this case:

Method "Circles«foo»②«bar none»?③«this|that»!④_†①" is
[
	t : number,
	foo : <⊥…|0>*,
	barNone : boolean,
	thisOrThat : [1..2]
|
	<t, foo, barNone, thisOrThat>
];
