### ISSUE TITLE
Deep improvements to the L2 optimizer

### ISSUE THREAD

**Issue by toddATavail** [AvailLang/Avail#22]
**Reported by mark on 8 Apr 2013 07:49 UTC**
The level two optimizer currently (2012.04.07) has numerous deficiencies.  This task is a catch-all for potential improvements, and will likely be split as boundaries between these potential changes clarify.

Deficiencies:

-It only inlines primitives.
-It's incapable of even representing, let alone optimizing, loops -- it simply creates full level one continuations and jumps into them.
-Decoding level two operations and operands out of a numeric tuple can't be anywhere near as efficient as keeping the level two instruction objects around and just telling them to step the interpreter.
-Register coloring is simplistic and inefficient.

It would also be nice to add:

-Keeping track of the provenance of values beyond simple moves would allow object deconstruction to be avoided in some cases.  For example, the expression <x,y,z>[2] should always produce the same value as y.  This becomes more useful after non-primitive inlining.  It also provides a simple but powerful form of object escape analysis.  In the example, the tuple <x,y,z> doesn't even have to be constructed if y is used instead of <x,y,z>[2].  The analysis should be done purely in level two terms by keeping track of which registers an object's subcomponents came from.  If "Rw ::= MakeTuple(Rx, Ry, Rz)" is followed eventually by "Ra ::= TupleAtConstant(Rw, #2)", and there are no intervening writes to Rw or Ry, then the second instruction can be replaced by "Ra ::= Ry".  This may make the write to Rw dead, eliminating the need to create the tuple at all.  We'll need a general way to describe which primitives are complementary in this sense.

-Polymorphic dispatch, where polymorphic call sites are dispatched via an embedded branch tree of type tests and branches.  This would allow some of the branches to be inlined, which is a pretty powerful mechanism.  A call site with narrow argument types would also be able to dispatch more efficiently than with the general dispatch tree stored in the Method itself.  I.e., it wouldn't have to consider types that are impossible at the site.  In addition, the branches would test a single argument at a time, potentially avoiding redundant tests for arguments that are effectively monomorphic or otherwise unproductive.  This last part would be useful in general for method dispatch, even without polymorphic inlined dispatch.

-Producing Java bytecodes for sufficiently used raw functions.  But continuations have to act "stackless"  not coupled to the Java stack.  An interesting best-of-both-worlds approach involves generating Java methods that test for a maximum safe Java stack depth explicitly, and when reached throw a ReifyContinuationsThrowable.  An exception handler in each such method synthesizes and accumulates (in reverse order) any necessary level one continuations.  If non-primitive inlining is implemented, a Java method may have to introduce multiple level one continuations.  The cleanest approach might be for each try/catch to produce a Transformer1<A_Continuation, A_Continuation>, the list of which will be folded in reverse order to produce the true level one stack.  While the normal optimistic flow simply returns its results through a Java return, after reification the return mechanism should be accomplished by invoking the main entry point with an auxiliary parameter set to the level one pc at which to continue.  The code inside can be structured as a switch with fall-throughs, one case per pc at which a return may re-enter.  Branches can be accomplished by modifying the level one pc variable (a copy of the auxiliary parameter) and performing a continue.  A while(true){...} outside the switch will simply make this an efficient jump (assuming things about HotSpot).  A return simply breaks this loop and returns to the code dealing with the outer continuation, whether it's a Java method version of a level two chunk or some other kind of caller.  Interrupts would also throw the ReifyContinuationsThrowable, as would non-inlined invocations of "Exit_" and "Restart_".

**Comment by toddATavail** [comment]
**Modified by mark on 30 May 2013 18:38 UTC**

**Comment by toddATavail** [comment]
**Comment by mark on 15 Sep 2013 04:50 UTC**
-Numeric L2 instructions are now replaced by real Java L2Instructions.
-Dispatch tree encoding in an integer tuple is now replaced by a Java LookupTree.
-The LookupTree now tests one argument at a time to reduce (in theory) redundant type checks).
-If the degree of applicable polymorphism is low enough, the lookup mechanism is encoded as type checks and branches in the L2 instructions.

**Comment by toddATavail** [comment]
**Modified by todd on 6 Apr 2014 16:55 UTC**

**Comment by markATavail** [comment]
Everything mentioned in the main issue seems to have been implemented to some degree.  Loop optimization currently only goes so far as to transform conditionally-invoked local labels into backward branches.  The speedup from this was substantial, but there is still no implementation of code splitting / loop customization.  Closing.
