### ISSUE TITLE
Workbench Module Tree Refresh Collapses Tree

### ISSUE THREAD

**Issue by richATavail** [AvailLang/Avail#258]
The module root tree (`AvailWorkbench.moduleTree`) does not remember what parts of the tree were visible on a refresh.  The view should be restored to what was visible only deviating from the view before the refresh if the visible branches/leaves are no longer part of the tree (the module/resource was deleted).

Begin tracing for fix from `avail.anvil.actions.RefreshAction.runAction()`.

**Comment by markATavail** [comment]
Fixed in development.
